# SITE CONFIGURATION
baseurl: ""
url: "https://wansook0316.github.io"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: ì™„ìˆ™ì˜ ì—ê·¸ë¨¸ë‹ˆğŸ³
  avatar: assets/img/avatar.png
  favicon: assets/favicon.ico
  gravatar: # Email MD5 hash
  description: "ì–¼ë–¨ê²°ì— ë“¤ì–´ì™”ìœ¼ë‹ˆ ì´ê²ƒë„ ì¸ì—°ğŸ˜Œ" # used by search engines

  # Header and footer text
  header_text: ì–¼ë–¨ê²°ì— ë“¤ì–´ì™”ìœ¼ë‹ˆ ì´ê²ƒë„ ì¸ì—°
  header_text_feature_image: assets/img/background_minion.jpg
  footer_text: >
    ì´ì „ ë¸”ë¡œê·¸ <a href="https://egg-money.tistory.com">ì™„ìˆ™ì˜ ì—ê·¸ë¨¸ë‹ˆ</a>

  # Icons
  rss: false
  email_address: "wansook0316@gmail.com"
  # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  gitlab:
  github: "wansook0316"
  gitter:
  google_plus:
  instagram:
  linkedin: # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange: # Full URL
  steam:
  tumblr:
  twitter:
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-156961472-1"
  disqus_shortname: "wansook0316"
  katex: true # Enable if using math markup
  search: true # Enable the search feature

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."
  str_search_no_results: "No results found."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  # default fonts
  # google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  google_fonts: "Nanum+Gothic|Jua|Nanum+Gothic+Coding|Source+Code+Pro|Nanum+Myeongjo:400|Noto+Sans+KR:100,300"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate]
exclude:
  - Gemfile
  - Gemfile.lock
exclude: [vendor]